include:
  - docker-compose-infra.yml
services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    stop_grace_period: 5s
    environment:
      APP_HOME: /app
      APP_LOG_HOME: /app/log
      JAVA_OPTS: -Xms128m -Xmx256m -XX:+UnlockDiagnosticVMOptions -XX:+LogVMOutput -XX:LogFile=/app/jvm.log
      APP_OPTS: -Dconfig.file=/app/application.conf -Dlogback.configurationFile=/app/logback.xml -Dproject.config.dir=/app -Dswaggerui.dir=/app/swagger-ui -Duser.timezone=UTC -Dkotlinx.coroutines.debug -Dotel.javaagent.enabled=true -javaagent:/app/lib/opentelemetry-javaagent.jar -Dotel.javaagent.configuration-file=/app/otel-javaagent.properties
      PORT: 8080
      SERVER_SHUTDOWN_KEY: changeit
      INFRA_DB_URL: jdbc:postgresql://postgres:5432/infra
      INFRA_DB_USER: configure it
      INFRA_DB_PASSWORD: changeit
      OPS_DB_URL: jdbc:postgresql://postgres:5432/ops
      OPS_DB_USER: configure it
      OPS_DB_PASSWORD: changeit
      CLUB_DB_URL: jdbc:postgresql://postgres:5432/club
      CLUB_DB_USER: configure it
      CLUB_DB_PASSWORD: changeit
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SWAGGER_UI_PATH: /app/swagger-ui
      SWAGGER_UI_AUTH_USER: swagger
      SWAGGER_UI_AUTH_PASSWORD: changeit
      GOOGLE_APPLICATION_CREDENTIALS: /app/firebase-key.json
      SENTRY_DSN: configure it
      SENDGRID_API_KEY: configure it
      TWILIO_ACCOUNT_SID: configure it
      TWILIO_AUTH_TOKEN: configure it
      TWILIO_FROM_PHONE_NUMBER: configure it
      LOKI_USERNAME: configure it
      LOKI_PASSWORD: configure it
      # ===== subproject ops =====
      OPS_AUTH_ROOT_API_KEY: changeit
      OPS_AUTH_MONITOR_API_KEY: changeit
      OPS_AUTH_USER_API_KEY: changeit
      # ===== subproject club =====
      CLUB_AUTH_ROOT_API_KEY: changeit
      CLUB_AUTH_ANDROID_API_KEY: changeit
      CLUB_AUTH_ANDROID_RUNAS_KEY: changeit
      CLUB_AUTH_IOS_API_KEY: changeit
      CLUB_AUTH_IOS_RUNAS_KEY: changeit
    depends_on:
      - postgres
      - redis